sweet_cms/applications/base/forms.py
# -*- coding: utf-8 -*-
"""Public forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired

from sweet_cms.applications.user.models import User


class LoginForm(FlaskForm):
    """Login form."""

    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append("Unknown username")
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append("Invalid password")
            return False

        if not self.user.active:
            self.username.errors.append("User not activated")
            return False
        return True

sweet_cms/applications/base/__init__.py
from . import views 

sweet_cms/applications/base/views.py
from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import login_required, login_user, logout_user

from sweet_cms.extensions import login_manager
from sweet_cms.applications.base.forms import LoginForm
from sweet_cms.applications.user.forms import RegisterForm
from sweet_cms.applications.user.models import User
from sweet_cms.utils import flash_errors
blueprint = Blueprint("base", __name__, static_folder="./static", template_folder='templates')


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route("/", methods=["GET", "POST"])
def home():
    """Home page."""
    form = LoginForm(request.form)
    current_app.logger.info("Hello from the home page!")
    # Handle logging in
    if request.method == "POST":
        if form.validate_on_submit():
            login_user(form.user)
            flash("You are logged in.", "success")
            redirect_url = request.args.get("next") or url_for("user.members")
            return redirect(redirect_url)
        else:
            flash_errors(form)
    return render_template("public/home.html", form=form)


@blueprint.route("/logout/")
@login_required
def logout():
    """Logout."""
    logout_user()
    flash("You are logged out.", "info")
    return redirect(url_for("base.home"))


#login    
@blueprint.route("/login/" , methods=["GET", "POST"])
def login():
    """Login."""
    if request.method=="GET":
         form = LoginForm()
         return render_template("public/login.html", form=form)
  
    # Handle logging in
    elif request.method == "POST":
         form = LoginForm(request.form)
         if form.validate_on_submit():
             login_user(form.user)
             flash("You are logged in.", "success")
             redirect_url = request.args.get("next") or url_for("user.members")
             return redirect(redirect_url)
         else:
             flash_errors(form)
    return render_template("public/home.html")

      


@blueprint.route("/register/", methods=["GET", "POST"])
def register():
    """Register new user."""
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        User.create(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
            active=True,
        )
        flash("Thank you for registering. You can now log in.", "success")
        return redirect(url_for("base.home"))
    else:
        flash_errors(form)
    return render_template("public/register.html", form=form)


@blueprint.route("/about/")
def about():
    """About page."""
    form = LoginForm(request.form)
    return render_template("public/about.html", form=form)

sweet_cms/applications/base/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('base.home')}}">log in</a> or
            <a href="{{ url_for('base.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

sweet_cms/applications/base/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>Copyright {{ today.year }} © Sweet CMS</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('base.about') }}">About</a></li>

      <li><a href="mailto:admin@sweetcms.com">Contact</a></li>
    </ul>
  </small>
</footer>

sweet_cms/applications/base/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
  <meta charset="utf-8" />

  <link rel="shortcut icon" href="{{url_for('static', filename='web/img/favicon.ico') }}">
  <title>
    {% block page_title %}
    Sweet CMS
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}" />
  <meta name="author" content="{% block meta_author %}{% endblock %}" />

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width" />

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='web/main_css.bundle.css') }}" />

  {% block css %}{% endblock %}
</head>

<body class="{% block body_class %}{% endblock %}">
  {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

  <header>{% block header %}{% endblock %}</header>

  <main role="main">
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
          {{ message }}
        </div>
        <!-- end .alert -->
        {% endfor %}
      </div>
      <!-- end col-md -->
    </div>
    <!-- end row -->
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  </main>

  {% include "footer.html" %}

  <!-- JavaScript at the bottom for fast page loading -->
  <script src="{{ url_for('static', filename='web/main_js.bundle.js') }}"></script>
  {% block js %}{% endblock %}
  <!-- end scripts -->
  {% endblock %}
</body>

</html>

sweet_cms/applications/base/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('base.home') }}">
     Sweet CMS 
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('base.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item-active">
        <a class="nav-link" href="{{ url_for('base.about') }}">About</a>
      </li>
      {% if current_user and current_user.is_authenticated %}
      <!-- Live Streaming List -->
     
      <!-- End LIve Streaming  -->
      
    </ul>
    {#% if current_user and current_user.is_authenticated %#}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item-active">
        <a class="nav-link" href="{{ url_for('base.logout') }}">Log-Out
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
   <li class="nav-item-active">
        <a class="nav-link" href="{{ url_for('base.login') }}">Log-in
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    <ul class="navbar-nav my-auto">
      <li class="nav-item-active">
        <a class="nav-link navbar-text" href="{{ url_for('base.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>

sweet_cms/applications/base/templates/users/footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com
            {{ today.year }}</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
            Free
            <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin
                templates</a>
            from Bootstrapdash.com</span>
    </div>
</footer>

sweet_cms/applications/base/templates/users/live_strem.html
{% extends "public/base.html" %}
{% block content %}
    <div class="container-scroller">
      {% include 'users/sidebar.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_navbar.html -->
        {% include 'users/navbar.html' %}
        <!-- partial -->
         <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <h3 class="mt-5">Live Streaming</h3>
            
<div class="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
           
            </div>
            <div class="col-12 col-lg-12 ">
                <div class="card">
                    <div class="card-body">
                       
                        
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="videos-tab" data-toggle="tab" href="#videos"
                                        role="tab" aria-controls="videos" aria-selected="false">
                                        <span class="d-block d-sm-none"><i class="fa fa-home"></i></span>
                                        <span class="d-none d-sm-block">live programs</span>
                                    </a>
                                </li>
                               
                            </ul>
                            
                                                                                                                             
                            <div class="tab-content">
                                <div class="tab-pane fade active show" id="videos" role="tabpanel"
                                    aria-labelledby="videos-tab">
                                    
                                      
                                    <div class="card flex-row flex-wrap">
                                        <div class="card-header border-0 w-250" >
                                            
                                          
                                            <video class="w-100 h-100"  id="myvideo"  autoplay muted playsinline 
                                         
                                            {% for programme in programme  %}
                                        
                                            {% for file in programme.banners %}
                                           

                                             {% if   file.file_status=='live' %}
                                             
                                            poster="{{ url_for('admin.eventy_uploaded', file_path=file.file_url) }}">
                                           
                                                {% for file in programme.videos %}
                                                
                                                <source
                                                class="active"
                                                    src="{{ url_for('admin.eventy_uploaded', file_path=file.file_url) }}" type="video/mp4"> 
                                                {% else %}
                                                <source
                                                class=""
                                                    src="">
                                                
                                                    
                                                {% endfor %}
                                                {% else %}
                                                 
                                                {% endif %}
                                                {% endfor %}
                                               
                                            </video>

                                        </div>
                                
                                      
                               {% endfor %}
                               
                                </div>
                            </div>
                            
                    </div>
                </div>
            </div>
            
          </div>
          
   
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          {% include 'users/footer.html' %}
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

                <script>
                var myvid = document.getElementById('myvideo');
                // console.log(myvid)
                debugger

                myvid.addEventListener('ended', function(e) {
                // get the active source and the next video source.
                // I set it so if there's no next, it loops to the first one
                var activesource = document.querySelector("#myvideo source.active");
                var nextsource = document.querySelector("#myvideo source.active + source") || document.querySelector("#myvideo source:first-child");
                
                // deactivate current source, and activate next one
                activesource.className = "";
                nextsource.className = "active";

                // update the video source and play
                myvid.src = nextsource.src;
                myvid.play();
                });

            </script> 
        <script>/*
            *  Copyright (c) 2016 The WebRTC project authors. All Rights Reserved.
            *
            *  Use of this source code is governed by a BSD-style license
            *  that can be found in the LICENSE file in the root of the source
            *  tree.
            */
            'use strict';
            
            const leftVideo = document.getElementById('myvideo');
            const rightVideo = document.getElementById('rightVideo');
            
            leftVideo.addEventListener('canplay', () => {
              let stream;
              const fps = 0;
              if (leftVideo.captureStream) {
                stream = leftVideo.captureStream(fps);
              } else if (leftVideo.mozCaptureStream) {
                stream = leftVideo.mozCaptureStream(fps);
              } else {
                console.error('Stream capture is not supported');
                stream = null;
              }
              rightVideo.srcObject = stream;
            });</script>
            <script>
                var vid = document.getElementById("myVideo");
vid.autoplay = true;
vid.load();
            </script>
           

           
            {% endblock %}
            

sweet_cms/applications/base/templates/users/members.html
{% extends "public/base.html" %}
{% block content %}
    <!-- <div class="container">
        <h1>Welcome {{ current_user.username }}</h1>
        <h3>This is the members-only page.</h3>
    </div> -->
    <div class="container-scroller">
      <!-- partial:partials/_sidebar.html -->
      {% include 'users/sidebar.html' %}
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_navbar.html -->
        {% include 'users/navbar.html' %}
        <!-- partial -->
         <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          {% include 'users/footer.html' %}
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
{% endblock %}

sweet_cms/applications/base/templates/users/navbar.html
<nav class="navbar p-0 fixed-top d-flex flex-row">
          <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
            <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{ url_for('static', filename='web/public/images/logo-mini.svg') }}" alt="logo" /></a>
          </div>
          <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
              <span class="mdi mdi-menu"></span>
            </button>
            <ul class="navbar-nav w-100">
              <li class="nav-item w-100">
                <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                  <input type="text" class="form-control" placeholder="Search products">
                </form>
              </li>
            </ul>
            <ul class="navbar-nav navbar-nav-right">
              <li class="nav-item dropdown d-none d-lg-block">
                
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="createbuttonDropdown">
                  <h6 class="p-3 mb-0">Projects</h6>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-file-outline text-primary"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1">Software Development</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-web text-info"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1">UI Development</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-layers text-danger"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1">Software Testing</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <p class="p-3 mb-0 text-center">See all projects</p>
                </div>
              </li>
              <li class="nav-item nav-settings d-none d-lg-block">
                <a class="nav-link" href="#">
                  <i class="mdi mdi-view-grid"></i>
                </a>
              </li>
              <li class="nav-item dropdown border-left">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                  <i class="mdi mdi-email"></i>
                  <span class="count bg-success"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                  <h6 class="p-3 mb-0">Messages</h6>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <img src="assets/images/faces/face4.jpg" alt="image" class="rounded-circle profile-pic">
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1">Mark send you a message</p>
                      <p class="text-muted mb-0"> 1 Minutes ago </p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <img src="assets/images/faces/face2.jpg" alt="image" class="rounded-circle profile-pic">
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1">Cregh send you a message</p>
                      <p class="text-muted mb-0"> 15 Minutes ago </p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <img src="assets/images/faces/face3.jpg" alt="image" class="rounded-circle profile-pic">
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1">Profile picture updated</p>
                      <p class="text-muted mb-0"> 18 Minutes ago </p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <p class="p-3 mb-0 text-center">4 new messages</p>
                </div>
              </li>
              <li class="nav-item dropdown border-left">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                  <i class="mdi mdi-bell"></i>
                  <span class="count bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                  <h6 class="p-3 mb-0">Notifications</h6>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-calendar text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">Event today</p>
                      <p class="text-muted ellipsis mb-0"> Just a reminder that you have an event today </p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-settings text-danger"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">Settings</p>
                      <p class="text-muted ellipsis mb-0"> Update dashboard </p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-link-variant text-warning"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">Launch Admin</p>
                      <p class="text-muted ellipsis mb-0"> New admin wow! </p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <p class="p-3 mb-0 text-center">See all notifications</p>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                  <div class="navbar-profile">
                    <img class="img-xs rounded-circle" src="{{ url_for('static', filename='assets/images/faces/face15.jpg')}}" alt="">
                    <p class="mb-0 d-none d-sm-block navbar-profile-name">{{ current_user.username|title }}</p>
                    <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                  </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                  
                   <a class="dropdown-item preview-item" href="{{url_for('user.profile')}}">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-account text-primary"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">profile</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item" href="#">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-settings text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">Settings</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item" href="{{url_for('base.logout')}}">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-logout text-danger"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">Log out</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <p class="p-3 mb-0 text-center">Advanced settings</p>
                </div>
              </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
              <span class="mdi mdi-format-line-spacing"></span>
            </button>
          </div>
        </nav>